logging:
  level:
    ROOT: info
    fi.joufa.safetor: debug

spring:
  profiles:
    active: dev

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:mem:teams;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: teamsapp
    password:
